packages:
  - bc
  - binutils
  - elfutils-libelf
  - fontconfig-devel
  - glibc
  - glibc-devel
  - ksh
  - libaio
  - libaio-devel
  - libXrender
  - libXrender-devel
  - libX11
  - libXau
  - libXi
  - libXtst
  - libgcc
  - librdmacm-devel
  - libstdc++
  - libstdc++-devel
  - libxcb
  - make
  - smartmontools
  - sysstat
  - xorg-x11-utils

preq_packages:                
  - kernel-headers-3.10.0-1127.8.2.el7.x86_64.rpm                  
  - ksh-20120801-142.el7.x86_64.rpm                
  - compat-libcap1-1.10-7.el7.x86_64.rpm          
  - libaio-devel-0.3.109-13.el7.x86_64.rpm         
  - compat-libstdc++-33-3.2.3-72.el7.x86_64.rpm                   
  - oracle-database-preinstall-19c-1.0-1.el7.x86_64.rpm          
  - libstdc++-4.8.5-39.el7.x86_64.rpm                 
  - libstdc++-devel-4.8.5-39.el7.x86_64.rpm        
  - ntp-4.2.6p5-29.el7.centos.x86_64.rpm
  - ntpdate-4.2.6p5-29.el7.centos.x86_64.rpm
  - autogen-libopts-5.18-5.el7.x86_64.rpm
  - glibc-2.17-260.el7.x86_64.rpm
  - glibc-common-2.17-260.el7.x86_64.rpm
  - glibc-devel-2.17-260.el7.x86_64.rpm
  - glibc-headers-2.17-260.el7.x86_64.rpm
